spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 654321
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://39.108.160.171:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
      default-property-inclusion: non_null
  redis:
      host: 39.108.160.171
      port: 6379
server:
  servlet:
    context-path: '/sell'

#wechat:
#  mpAppId: wxd898fcb01713c658
#  mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
#  openAppId: wx6ad144e54af67d87
#  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
#  mchId: 1483469312
#  mchKey: 06C56A89949D617xxxxxxxxxxx
#  keyPath: /var/weixin_cert/h5.p12
#  notifyUrl: http://kafun.natapp1.cc/sell/pay/notify
#  templateId:
#    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projecturl:
  wechatMpAuthorize: http://localhost:8080
  wechatOpenAuthorize: http://localhost:8080
  sell: http://localhost:8080
#  sell: http://sell.natapp4.cc
